redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\yaser\\Desktop\\RAG_PROJECT_V7"
publishOrigin = "config"
commandOrigin = "config"
command = "echo 'No build required'"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/rag_project_v6_2.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]